### ISSUE TITLE
Remove h2 in server implementation

### ISSUE THREAD

**Issue by ulrikstrid** [reason-native-web/morph#17]
Needing http2 is probably not something we have to support. We should just delete this code.

Another solution is to refactor it so that you pass in a server implementation from the outside, but this might be a larger issue.

If anyone needs this support please comment here.

**Comment by baransu** [comment]
I'm not sure how many people need it but it would be good to support both HTTP/1.1 and HTTP/2.0. But if maintenance overhead is too large we could drop it 🤷‍♂️

**Comment by ulrikstrid** [comment]
This is partly done, I have just not updated the issue to reflect the current state.

I refactored so that we pass in server(s) that we then give the middleware stack to.
The H2 implementation now lives in morph_server_https. We could in theory split it out even further but it might be good enough for now.

**Comment by ulrikstrid** [comment]
To reduce my maintenance burden I decided to move over to Piaf which only uses http1 for the server parts.
