### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ulrikstrid** [reason-native-web/morph#29]
We want to support Windows at least the client but preferably everything.

**Comment by ulrikstrid** [comment]
Blocker for Httpaf (Faraday in truth) https://github.com/ocsigen/lwt/issues/745

**Comment by lessp** [comment]
This is incoming in: https://github.com/ocaml/opam-repository/pull/15536 thanks to Anton!

**Comment by zetashift** [comment]
It is also now merged and closed so it there shouldn't be any blockers now?

**Comment by ulrikstrid** [comment]
@zetashift I have just not tested it yet but in theory it should just work

**Comment by ManasJayanth** [comment]
Just an update: Morph works fine on Windows. I was using it until recently when I needed postgres - libpsql doesn't build on Windows.

**Comment by ulrikstrid** [comment]
I feel confident in closing this now. Thanks for verifying @ManasJayanth
