### ISSUE TITLE
Remove resolutions

### ISSUE THREAD

**Issue by wokalski** [reason-native-web/morph#32]
The resolutions make it quite painful to integrate morph in a project. Is the antonio's httpaf fork required? Can it be replaced with anything from opam/esy (h2?)?

**Comment by ulrikstrid** [comment]
Since the standard httpaf isn't really maintained we have to use @anmonteiro's fork, h2 "only" handles http2.
I have hoped to get a release of the fork for a while but it seems like it will not happen in the current form.

**Comment by wokalski** [comment]
@ulrikstrid consider publishing them under @reason-native-web just to have it on npm. Currently it's a real pain to get everything going.

**Comment by ulrikstrid** [comment]
This is now fixed and in master
